### ISSUE TITLE
请问，搜索PT最新的网页端是多少？

### ISSUE THREAD

**Issue by 1990chs** [Rhilip/PT-help-server#1]
RT，https://rhilip.github.io/PT-help-server/ptboard
上面的界面打不开了，搜到这里，请问最新的网页版的地址是什么呢？谢谢！

**Comment by Rhilip** [comment]
Git-Pages已恢复，之前因部分原因导致关闭。
你可以选择下载 `/docs` 目录下的相关html页面并打开。
