### ISSUE TITLE
ptgen输入电影名点击查询后未生成电影信息

### ISSUE THREAD

**Issue by xoyabc** [Rhilip/PT-help-server#13]
RT,还请抽空给看一眼，多谢。
[https://rhilip.github.io/PT-help/ptgen](https://rhilip.github.io/PT-help/ptgen)
![1.gif](https://i.loli.net/2018/05/29/5b0c3eae255c8.gif)

**Comment by Rhilip** [comment]
抱歉，这段是前端来做的，之前忘记写相关逻辑了Orz
现在应该可以了

**Comment by xoyabc** [comment]
@Rhilip，可以显示了，感谢~
刚才搜索“血战钢锯岭”时“良心拒服兵役者”也出来了，帮忙看下这种情况能优化下吗？个人感觉可能是豆瓣返回就是这样的。

**Comment by xoyabc** [comment]
@Rhilip，可以显示了，感谢~
刚才搜索“血战钢锯岭”时“良心拒服兵役者”也出来了，帮忙看下这种情况能优化下吗？个人感觉可能是豆瓣返回就是这样的。

**Comment by Rhilip** [comment]
@xoyabc 这块直接调用豆瓣的搜索接口，直接选择需要的就行。应该做不了优化

**Comment by xoyabc** [comment]
好的，感谢
