### ISSUE TITLE
Deploy ptsearch on vps issue?

### ISSUE THREAD

**Issue by inevity** [Rhilip/PT-help-server#18]
flask route / to ptboard.html.But when access, show Please input your token to access Pt-Board. How to deal with it?

**Comment by Rhilip** [comment]
ptsearch is not a vps part project, It's userscript with a front-page (like [BT MetaSearch](https://greasyfork.org/en/scripts/12013-bt-metasearch) )
So If you want to use pt-search, It's only need the git-page (Which can open in repo settings) and the userscript in `docs/js` which named `ptsearch.user.js`.

**Comment by inevity** [comment]
I know, I have deployed  the PT-help project on vps. and can access ptsearch now.
But when access ptboard, the dialog "Please input your token to access Pt-Board"

I use code in flask:
@app.route('/')
def root():
    return app.send_static_file('ptboard.html')

**Comment by Rhilip** [comment]
The default Pt-Board app fetch the data from my private  API (Which now need token to access, see this commit https://github.com/Rhilip/PT-help/commit/74b2f37dadcac906d2751a8eeeb5fdf95668dd1e) 

--------------------

To Deploy your own Pt-Board app , you should following those steps:
1. Install Mysql and set it's seting in flask Config.
2. restore Mysql database from file : [ptboard_record.sql](https://github.com/Rhilip/PT-help/blob/master/modules/ptboard/db/ptboard_record.sql)
3. Use Other script to crawler the publish info from PT-site and record in database. **(My crawler script is not public now)**
The data stored in database like : 

> table `ptboard_site`
![image](https://user-images.githubusercontent.com/13842140/48828516-e6f77380-edaa-11e8-97e7-e20d3f9c280d.png)
> table `ptboard_record`
![image](https://user-images.githubusercontent.com/13842140/48828576-10b09a80-edab-11e8-88e4-8e774f28051b.png)
> table `ptboard_token`
![image](https://user-images.githubusercontent.com/13842140/48828749-8b79b580-edab-11e8-97bc-9df62696bdc9.png)

4. Set your private token in table `ptboard_token` with length `32`.
5. Change the API url in static file `ptboard.html`.

**Comment by inevity** [comment]
Thank your very much. I will follow it.
