### ISSUE TITLE
ptgen搜索空白

### ISSUE THREAD

**Issue by zlhdd108** [Rhilip/PT-help-server#26]
问题现象：通过https://rhilip.github.io/PT-help/ptgen 搜索电影名字，然后点击“选择”，然后等到查找完成，内容却是空白的
截图:
1.
![image](https://user-images.githubusercontent.com/16465666/56019939-84dae300-5d38-11e9-843f-76c33887e8cd.png)
2.
![image](https://user-images.githubusercontent.com/16465666/56019964-92906880-5d38-11e9-9184-46f247275abc.png)
3.
![image](https://user-images.githubusercontent.com/16465666/56019980-9a500d00-5d38-11e9-987e-a0749b2108bb.png)
![image](https://user-images.githubusercontent.com/16465666/56019988-9f14c100-5d38-11e9-92dc-fc89d34623d0.png)

**Comment by Rhilip** [comment]
结果命中了之前的数据库缓存
因为之前的数据库缓存是OurBits提供的，处理过程中使得里面缺少了一个前端使用的判断字段，已修复。
