### ISSUE TITLE
无法生成Bangumi简介，返回Internal error : None

### ISSUE THREAD

**Issue by moomiji** [Rhilip/PT-help-server#27]
连续3天无法查询，好像是更新之后出现的问题？
豆瓣查询正常。
![image](https://user-images.githubusercontent.com/35213527/56075361-017ec780-5df4-11e9-9def-7278b7ebb46d.png)

**Comment by Rhilip** [comment]
修好了，等等我推到线上
https://github.com/Rhilip/PT-help/commit/bfbf6dcde78b0c4b92ae9729866ce263077350db#diff-02bc96f903d68ec3c11cdb529640fcfeR541
