### ISSUE TITLE
很棒的工具,不过mt似乎搜不到

### ISSUE THREAD

**Issue by wgf0330** [Rhilip/PT-help-server#3]
![20180110205625](https://user-images.githubusercontent.com/18156721/34774026-d016b22a-f648-11e7-818b-eb0e1fa63ee7.jpg)
试了几次,都没有mt的结果

**Comment by Rhilip** [comment]
请按照此意见修改issue。 https://github.com/Rhilip/PT-help/issues/2
并取消其他站点的搜索设置。

-------

本人未发现MT搜索存在任何问题，但是因为该站存在二次验证跳转的原因，请确认你是在直接打开页面不会提示二次验证的情况再尝试搜索。

**Comment by Rhilip** [comment]
我未收到你任何更新信息，Close。
如有需要请open or new issue
