### ISSUE TITLE
shabang 中文叹号

### ISSUE THREAD

**Issue by rachpt** [Rhilip/PT-help-server#30]
https://github.com/Rhilip/PT-help/blob/69b5e84abe24056931e9752770243b260855ba38/modules/infogen/gen.py#L1
第一行的 shabang 应该是 `#!` 而不是 `#！`吧，并且两个符号之间没有空格。

否则 shabang 无效。

估计你的 pycharm header 模板打错了，Pt-Autoseed 的 run.py 也是  :joy:

![MQpk2d.png](https://s2.ax1x.com/2019/11/11/MQpk2d.png)

**Comment by Rhilip** [comment]
早年啥都不懂，被垃圾中文教程给坑了😂😂😂
