### ISSUE TITLE
脚本突然完全失效

### ISSUE THREAD

**Issue by bimzcy** [Rhilip/PT-help-server#4]
脚本突然完全失效了，昨天和前天用着都OK，今天突然就不行了，什么结果都搜不出来了。版本：v20180111

无论是火狐上的暴力猴还是谷歌上的Tampermonkey都突然不行了。

**Comment by Rhilip** [comment]
抱歉，我的锅，昨天添加功能的时候写错了变量名。
可以先回退到上一个版本或者手动更新到今天的版本( https://github.com/Rhilip/PT-help/commit/949eb9d1e3cf8b3837897c237d2d1c0e10dff60c )。
该问题已解决。
