### ISSUE TITLE
HDU/OpenCD无法搜索

### ISSUE THREAD

**Issue by ghost** [Rhilip/PT-help-server#5]
#用户平台： Win7 SP1 x64   QQ浏览器v9.7(12661)    暴力猴v2.8.28
用户脚本版本： 20180206.1？ 不太明白怎么看，总之点Raw添加的，最新的
启用搜索站点： HDU OpenCD
搜索关键词： 任意字符
搜索Log： 已启用full log，没有多余的报错信息，就提示Not Login in site HDU / OpenCD 
Console面板信息： 不知道应该如何提供这项 建议明示 方便他人反馈~

这两个站点，手动点开都是已登录的状态。已尝试退出重新登录、删掉cookies和保存的账户密码重新登录等。
其他多个已有站点没遇到任何问题。

还望帮助，谢谢

**Comment by Rhilip** [comment]
抱歉，我在我这边模拟并没有出现在已经登陆的情况下脚本提示未登陆（环境：Chrome 63 + Tampermonkey v4.5），此外本人不是专业的前端测试员，也不可能尝试国产浏览器。
在 https://github.com/Rhilip/PT-help/commit/079b389fe815a134d62a9873a0c002d55d082b88 中，我尝试添加了一个取消脚本登陆检查的选项，以及在启用登陆检查的情况下，输出脚本搜索时最终的链接（在可能后台请求出现登陆的情况下）。请尝试启用和取消该选项，检查这两个站点是否能够正常搜索。（你需要更新脚本到20180222或更高版本）
在 https://github.com/Rhilip/PT-help/commit/aa7ed11564f16c1649639c4699537784f33d4438 中，我补加了部分报错抛出的功能。
希望能帮助到你，如果你有更新的进展，请留言。

-----------------

关于在调试过程中发现OpenCD的获取信息不正常现象，我将在该站站免结束后修复。

**Comment by ghost** [comment]
...你好，抱歉现在才回复。前一阵一直没空。
。。你加入的这个功能很有效，瞬间搞明白了具体原因。
这两个网站我使用的网址，和你的不同，所以导致了问题

HDU: [pt.upxin.net](https://pt.upxin.net) OpenCD: [open.cd](https://open.cd)
所以当然就提示没登录了。。

**Comment by LC-BX** [comment]
你好：
感谢你的更新，我已经定位了问题，已回复到issue里。




by LC
在2018年2月22日 23:08，Rhilip<notifications@github.com> 写道：
抱歉，我在我这边模拟并没有出现在已经登陆的情况下脚本提示未登陆。（环境：Chrome 63 + Tampermonkey v4.5），此外本人不是专业的前端测试员，也不可能尝试国产操作系统。
在 079b389 中，我尝试添加了一个取消脚本登陆检查的选项，以及在启用登陆检查的情况下，输出脚本搜索时最终的链接（在可能后台请求出现登陆的情况下）。
请尝试启用和取消该选项，检查这两个站点是否能够正常搜索。
希望能帮助到你，如果你有更新的进展，请留言。

关于在调试过程中发现OpenCD的获取信息不正常现象，我将在接下去几个相关commit中修复。

**Comment by Rhilip** [comment]
这是一个很麻烦的问题，因为脚本目前采用异步回调的形式来进行页面获取与解析。在原先的计划中并没有为同一个站点不同的域名进行适配。
我尽量尝试针对这一现象进行修正，在此之前建议使用脚本目前使用的域名进行登陆与访问。

**Comment by Rhilip** [comment]
我想了了想，是否可以考虑把一些细节给公开出来。比如NexusPHP系站点多数可以采用同一模板进行解析，这部分可以放开给用户自己配置。比如举个例子
`NexusPHP("HDSKY", "https://hdsky.me/", "https://hdsky.me/torrents.php?search=", ".torrents tr.progresstr");`
多数站点可以使用类似该行的进行解析，那么这里使用的4个参数可以直接放开给用户自配置。
这种解决方法是我觉得避免该issue的一种较为合适的方法，此外该方法也可以让用户快速添加一些站点或者修改搜索字段（比如增加搜索条件）。。

————————
不过这样的话我可能会对脚本和网页做一些大的修改。
