### ISSUE TITLE
你好，请问下pt-search 不能选择CCF？

### ISSUE THREAD

**Issue by fengchen8611** [Rhilip/PT-help-server#6]
pt-search选择站点时 不能选择CCF，如何解决？还有外站 如何使用BT MetaSearch

**Comment by Rhilip** [comment]
CCF暂时无支持计划。
BT MetaSearch 不是本人作品，无介绍使用方法的义务。请自己查阅对应的插件。

**Comment by fengchen8611** [comment]
好的，谢谢答复

2018-03-11 19:27 GMT+08:00 Rhilip <notifications@github.com>:

**Comment by Rhilip** [comment]
CCF 已支持。请更新脚本到20180331版本。
commit: https://github.com/Rhilip/PT-help/commit/8570214ad0d1b328661f416deb876de0bdeb09b6

**Comment by fengchen8611** [comment]
已正常使用
