### ISSUE TITLE
一个关于MT二次验证的问题

### ISSUE THREAD

**Issue by ghost** [Rhilip/PT-help-server#7]
嗯，首先说下，这个问题我已搞清楚原因，是由我独特的需求造成的。仅供作者参考。

打开MT，输入二次验证码，使用聚合搜索正常。

此时更改浏览器UA（通过浏览器插件），再次访问MT，重新输入二次验证码，聚合搜索（仅MT站）失效。

返回结果就是0（任意关键字）。此时恢复UA，重新访问MT并通过二次验证，即可恢复。

**Comment by Rhilip** [comment]
二次验证没过这个我也没办法 (￣▽￣)"
我已知的就是MT的二次验证对User Agent和IP均会检测，任何一个与上一次状态不同就会跳二次验证。。
脚本默认是使用`window.navigator.userAgent`（即浏览器自身的UA）作为UuserAgent的，你通过插件更改后就不一致了。。。
————————————
你可以在脚本任意合适位置插入 `console.log(window.navigator.userAgent);` 检查脚本当前的UA是不是你通过插件修改后的结果 :D

**Comment by ghost** [comment]
嗯对的 MT这个好严格~ 多谢回复，请close吧
